package guru.springframework.spring5recipeapp.domain;

import lombok.*;

import javax.persistence.*;

@Data
@EqualsAndHashCode(exclude = {"recipe"})
@Entity
public class Notes {

    //Identity only works with databases that support autogenerated id.
    //If using Oracle only works with Oracle 12.
    // Typically you want to use Long for id so you don't run out of id values for larger data sets
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    private Recipe recipe;

    //allows it to be persisted as a clob, which is larger than the string amount of 255 chars.
    @Lob
    private String recipeNotes;

}
