package guru.springframework.spring5recipeapp.domain;

import javax.persistence.*;

@Entity
public class Notes {

    //Identity only works with databases that support autogenerated id.
    //If using Oracle only works with Oracle 12.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne
    private Recipe recipe;

    //allows it to be persisted as a clob, which is larger than the string amount of 255 chars.
    @Lob
    private String recipeNotes;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Recipe getRecipe() {
        return recipe;
    }

    public void setRecipe(Recipe recipe) {
        this.recipe = recipe;
    }

    public String getRecipeNotes() {
        return recipeNotes;
    }

    public void setRecipeNotes(String recipeNotes) {
        this.recipeNotes = recipeNotes;
    }
}
